use_frameworks!

platform :ios, '8.0'

target 'ZLGImageRecognizeSDK_Example' do
  pod 'ZLGImageRecognizeSDK', :path => '../'

  target 'ZLGImageRecognizeSDK_Tests' do
    inherit! :search_paths

    
  end
end
